# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system          # Options: system, light, dark
  color: indigo           # Options: minimal, blue, navy, forest, indigo, rose, violet
                        # 'blue' or 'navy' fits your Snow/Ice theme best.

# SEO (Search Engine Optimization)
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'University of Trento'
    description: 'Personal academic website of John Mohd Wani, Cryosphere Researcher specializing in Snow Hydrology and Permafrost Modeling.'
    twitter: ''         # Add your handle (e.g. '@JohnWani') or leave empty

  analytics:
    google_analytics: '' # Add your ID (G-XXXXXXXX) later if you want tracking
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true # Allows visitors to toggle Dark/Light mode
    logo:
      text: 'John Mohd Wani' # <--- IMPORTANT: This changes the top-left name

# Site footer
footer:
  copyright:
    # I removed the license text for a cleaner look.
    notice: 'Â© {year} John Mohd Wani. All rights reserved.'
    license:
      enable: false      # Set to false to hide the Creative Commons icons in footer
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006' # US Format. Change to '2 Jan 2006' for European style.
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true         # <--- CRITICAL: Changed to TRUE so your equations render!
  privacy_pack:
    enable: false